

-- DROP TABLE public.personas;

CREATE TABLE public.personas (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(150) NULL,
	documento varchar(20) NOT NULL,
	email varchar(100) NULL,
	nombre varchar(100) NOT NULL,
	telefono varchar(15) NULL,
	tipo varchar(20) NOT NULL,
	activo BOOLEAN DEFAULT true NOT NULL,
	creado_por varchar(255) NULL,
	fecha_creacion timestamp(6) NULL,
	fecha_modificacion timestamp(6) NULL,
	modificado_por varchar(255) NULL,
	CONSTRAINT personas_pkey PRIMARY KEY (id),
	CONSTRAINT personas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PRESTATARIO'::character varying, 'PRESTADOR'::character varying])::text[]))),
	CONSTRAINT uk8ipe1ux0acdu4bb0yxdxlksro UNIQUE (documento)
);


-- DROP TABLE public.usuarios;

CREATE TABLE public.usuarios (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bloqueada bool NOT NULL,
	contrasenia varchar(200) NOT NULL,
	correo varchar(255) NULL,
	deshabilitada bool NOT NULL,
	nombre varchar(50) NOT NULL,
	CONSTRAINT ukio49vjba68pmbgpy9vtw8vm81 UNIQUE (nombre),
	CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

CREATE TABLE public.roles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NOT NULL,
	fecha_inicio timestamp NOT NULL,
	CONSTRAINT rol_pkey PRIMARY KEY (id)
	CONSTRAINT fkor5vdfg7bv12b37vaawa9lee2 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id)
);

-- DROP TABLE public.usuario_roles;

CREATE TABLE public.usuario_roles (
	id_usuario int4 NOT NULL,
	rol varchar(255) NOT NULL,
	fecha_inicio timestamp NOT NULL,
	CONSTRAINT usuario_roles_pkey PRIMARY KEY (id_usuario, rol),
	CONSTRAINT fkor5vdfg7bv12b37vaawa9lee2 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id)
);



-- DROP TABLE public.prestamos;

CREATE TABLE public.prestamos (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_creacion timestamp(6) NULL,
	fecha_modificacion timestamp(6) NULL,
	estado varchar(20) NOT NULL,
	fecha_inicio date NOT NULL,
	fecha_limite date NOT NULL,
	interes numeric(5, 2) NOT NULL,
	meses int4 NOT NULL,
	monto numeric(10, 2) NOT NULL,
	penalizacion numeric(5, 2) NULL,
	id_prestador int4 NOT NULL,
	id_prestatario int4 NOT NULL,
	creado_por varchar(255) NULL,
	modificado_por varchar(255) NULL,
	CONSTRAINT prestamos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'VENCIDO'::character varying])::text[]))),
	CONSTRAINT prestamos_pkey PRIMARY KEY (id),
	CONSTRAINT fkitb5s9o94cxqnb12jjgug5eyh FOREIGN KEY (id_prestatario) REFERENCES public.personas(id),
	CONSTRAINT fkp9nx6wlrifhwqs5frprafbfbk FOREIGN KEY (id_prestador) REFERENCES public.personas(id)
);






-- DROP TABLE public.notificaciones;

CREATE TABLE public.notificaciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descripcion varchar(255) NULL,
	destinatario_email varchar(100) NOT NULL,
	estado varchar(20) NOT NULL,
	fecha_envio timestamp(6) NOT NULL,
	id_prestamo int4 NOT NULL,
	CONSTRAINT notificaciones_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENVIADO'::character varying, 'FALLIDO'::character varying])::text[]))),
	CONSTRAINT notificaciones_pkey PRIMARY KEY (id),
	CONSTRAINT fk8l382qkad8rxr256sgtppd3h4 FOREIGN KEY (id_prestamo) REFERENCES public.prestamos(id)
);


-- DROP TABLE public.pagos;

CREATE TABLE public.pagos (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_creacion timestamp(6) NULL,
	fecha_modificacion timestamp(6) NULL,
	estado varchar(20) NOT NULL,
	fecha_pago date NULL,
	fecha_vencimiento date NOT NULL,
	monto numeric(10, 2) NOT NULL,
	id_prestamo int4 NOT NULL,
	creado_por varchar(255) NULL,
	modificado_por varchar(255) NULL,
	CONSTRAINT pagos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADA'::character varying, 'VENCIDA'::character varying])::text[]))),
	CONSTRAINT pagos_pkey PRIMARY KEY (id),
	CONSTRAINT fk7na2pyprg2mjqfhvynhig11mi FOREIGN KEY (id_prestamo) REFERENCES public.prestamos(id)
);

-- DROP TABLE public.garantias;

CREATE TABLE public.garantias (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descripcion text NOT NULL,
	estado varchar(20) NOT NULL,
	fecha_registro timestamp(6) NOT NULL,
	tipo varchar(50) NOT NULL,
	valor_estimado numeric(10, 2) NOT NULL,
	id_prestamo int4 NULL,
	id_pago int4 NULL,
	CONSTRAINT garantias_estado_check CHECK (((estado)::text = ANY ((ARRAY['EN_CUSTODIA'::character varying, 'DEVUELTA'::character varying, 'EJECUTADA'::character varying])::text[]))),
	CONSTRAINT garantias_pkey PRIMARY KEY (id),
	CONSTRAINT garantias_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ELECTRODOMESTICO'::character varying, 'JOYA'::character varying, 'VEHICULO'::character varying, 'PROPIEDAD'::character varying, 'OTRO'::character varying])::text[]))),
	CONSTRAINT fk_garantia_prestamo FOREIGN KEY (id_prestamo) REFERENCES public.prestamos(id)
	CONSTRAINT fk_garantia_pago FOREIGN KEY (id_pago) REFERENCES public.pago(id)
);


-- DROP TABLE public.documentos;

CREATE TABLE public.documentos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo varchar(150) NOT NULL,
	nombre varchar(255) NOT NULL,
	size numeric(12) NOT NULL,
	ruta varchar(255) NOT NULL,
	id_garantia int8 NULL,
	CONSTRAINT documentos_pkey PRIMARY KEY (id),
	CONSTRAINT fk_documentos_garantia  FOREIGN KEY (id_garantia) REFERENCES public.garantias(id)
);



INSERT INTO permisos (nombre, label, icon, route) VALUES
('VER_PERSONAS', 'Personas', 'account_circle', '/layout/persona'),
('VER_PRESTAMOS', 'Préstamos', 'paid', '/layout/prestamo'),
('VER_PAGOS', 'Pagos', 'attach_money', '/layout/pago'),
('VER_DOCUMENTOS', 'Documentos', 'description', '/layout/garantia');
('CREAR_PRESTAMO', 'Crear préstamo', 'add_circle', null),
('EDITAR_PRESTAMO', 'Editar préstamo', 'edit', null),
('ELIMINAR_PRESTAMO', 'Eliminar préstamo', 'delete', null);
('CREAR_PAGO', 'Crear pago', 'add_circle', null),
('EDITAR_PAGO', 'Editar pago', 'edit', null),
('ELIMINAR_PAGO', 'Eliminar pago', 'delete', null);
('CREAR_PERSONA', 'Crear persona', 'add_circle', null),
('EDITAR_PERSONA', 'Editar persona', 'edit', null),
('ELIMINAR_PERSONA', 'Eliminar persona', 'delete', null);
('CREAR_DOCUMENTO', 'Crear documento', 'add_circle', null),
('ELIMINAR_DOCUMENTO', 'Eliminar documento', 'delete', null);